### ISSUE TITLE
Wait For your Datasets And Environment

### ISSUE THREAD

**Issue by zhengkai930504** [YueWuHKUST/ICCV2021-Embedding-Novel-Views-in-a-Single-JPEG-Image#1]
Hi,I am following your works, and I am waiting for your environment files and other files.

**Comment by kathrinawu** [comment]
Please refer to the enviroment.yml for more details. The dataset id lists are updated. You can refer to Sec4.1 of main paper for more details. The MPIs are generated using their official code of StereoMag and PB-MPI.
